# JPA / Hibernate (Desarrollo)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicialización de Datos (data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Secreto JWT local para desarrollo (Evita que crashee si no configuras la variable en tu IDE)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
admin.password=Admin123$
